//
//  FoodCalories.swift
//  FoodieMate
//
//  Created by Robert Trifan on 30.05.2025.
//

// FoodCalories.swift

import Foundation

struct FoodCalories {
    static let caloriesDict: [String: Int] = [
        "pizza": 285,
        "apple": 52,
        "burger": 354,
        "banana": 89,
        "hotdog": 150,
        "carrot": 41,
        "broccoli": 55,
        "cake": 370,
        "rice": 130,
        "chicken breast": 165,
        "salmon": 208,
        "egg": 78,
        "cheese": 402,
        "milk": 42,
        "orange": 47,
        "strawberry": 33,
        "watermelon": 30,
        "cucumber": 16,
        "potato": 77,
        "tomato": 18,
        "onion": 40,
        "lettuce": 15,
        "peanut butter": 588,
        "almonds": 575,
        "yogurt": 59,
        "beef": 250,
        "pork": 242,
        "shrimp": 99,
        "tofu": 76,
        "spinach": 23,
        "peas": 81,
        "corn": 86,
        "mushroom": 22,
        "avocado": 160,
        "grapes": 69,
        "blueberry": 57,
        "chocolate": 546,
        "ice cream": 207,
        "pancakes": 227,
        "waffles": 291,
        "bacon": 541,
        "sausage": 301,
        "french fries": 312,
        "pasta": 131,
        "bagel": 250,
        "granola": 471,
        "honey": 304,
        "apple pie": 237,
        "donut": 195,
        "cookie": 160,
        "popcorn": 387,
        "soda": 140,
        "coffee": 2,
        "tea": 1,
        "water": 0,
        "beer": 153,
        "wine": 125,
        "chicken wings": 203,
        "lettuce salad": 33,
        "caesar salad": 190,
        "sushi": 200,
        "ramen": 436,
        "curry chicken": 280,
        "lobster": 89,
        "crab": 87,
        "clam": 74,
        "oyster": 68,
        "quinoa": 120,
        "lentils": 116,
        "black beans": 132,
        "chickpeas": 164,
        "edamame": 121,
        "cabbage": 25,
        "cauliflower": 25,
        "zucchini": 17,
        "eggplant": 25,
        "brussels sprouts": 43,
        "kale": 35,
        "mustard greens": 27,
        "beets": 43,
        "radish": 16,
        "celery": 16,
        "asparagus": 20,
        "artichoke": 47,
        "avocado toast": 250,
        "banana bread": 260,
        "carrot cake": 370,
        "chocolate cake": 371,
        "chocolate chip cookie": 160,
        "french bread": 265,
        "granola bar": 150,
        "guacamole": 152,
        "hamburger": 295,
        "hot dog": 150,
        "ice cream cone": 207,
        "jelly": 250,
        "macaroni and cheese": 310,
        "meatloaf": 280,
        "nachos": 346,
        "oatmeal": 158,
        "pancake syrup": 190,
        "peanut": 567,
        "pepperoni pizza": 298,
        "quesadilla": 290,
        "rice pudding": 209,
        "salad": 33,
        "salsa": 36,
        "shrimp cocktail": 99,
        "smoothie": 150,
        "spaghetti": 158,
        "steak": 271,
        "sushi roll": 200,
        "taco": 156,
        "tofu stir fry": 200,
        "turkey": 135,
        "vegetable soup": 70,
        "waffle cone": 291,
        // New unique items added:
        "fried eggs": 90,
        "scrambled eggs": 91,
        "boiled eggs": 78,
        "omelette": 154,
        "grilled chicken": 165,
        "fried chicken": 246,
        "mashed potatoes": 88,
        "baked potato": 161,
        "sweet potato": 86,
        "sweet potato fries": 150,
        "meatballs": 250,
        "spaghetti bolognese": 220,
        "lasagna": 240,
        "pizza margherita": 270,
        "cheeseburger": 303,
        "fish and chips": 430,
        "garden salad": 35,
        "vanilla ice cream": 207,
        "chocolate ice cream": 216,
        "blueberry muffin": 385,
        "crepes": 219,
        "coffee with milk": 30,
        "espresso": 5,
        "latte": 120,
        "cappuccino": 80,
        "hot chocolate": 190,
        "cola": 140,
        "lemonade": 99,
        "orange juice": 45,
        "apple juice": 46,
        "whiskey": 70,
        "vodka": 64,
        "tequila": 64,
        "gin": 64,
        "rum": 64,
        "mojito": 168,
        "margarita": 168,
        "piña colada": 245,
        "burrito": 320,
        "hummus": 166,
        "falafel": 333,
        "chili con carne": 250,
        "beef stew": 275,
        "clam chowder": 200,
        "banana smoothie": 200,
        "berry smoothie": 180,
        "green smoothie": 150,
        "protein shake": 250,
        "almond milk": 30,
        "soy milk": 54,
        "coconut milk": 45,
        "oat milk": 120,
        "orange soda": 150,
        "energy drink": 110,
        "peanut butter sandwich": 350,
        "cheese sandwich": 330,
        "turkey sandwich": 280,
        "ham sandwich": 310,
        "egg sandwich": 260,
        "club sandwich": 400,
        "caesar wrap": 350,
        "veggie burger": 270,
        "fish burger": 290,
        "chicken nuggets": 270,
        "fried rice": 250,
        "stir fry vegetables": 90,
        "grilled salmon": 208,
        "grilled steak": 271,
        "pasta alfredo": 310,
        "mac and cheese": 310,
        "beef tacos": 250,
        "chicken tacos": 230,
        "vegetable curry": 180,
        "fruit salad": 150,
        "cottage cheese": 98,
        "greek yogurt": 59,
        "toasted bread": 120,
        "baguette": 270,
        "croissant": 300,
        "muffin": 385,
        "pizza pepperoni": 298
    ]
}
